pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                 dir("team-service") {
                    sh 'ls'
                 }
            }
        }
        stage('Test') {
            steps {
                echo 'Testing..'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
    }
}
