pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                 sh 'cd team-service'
                 sh './gradlew clean build'
            }
        }
        stage('Test') {
            steps {
                echo 'Testing..'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
    }
}
