pipeline {
    agent any

    tools {
        jdk 'jdk8'
    }

    stages {
        stage('Build') {
            steps {
                 sh './gradlew clean build'
            }
        }
        stage('Test') {
            steps {
                echo 'Testing..'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
    }
}
